### ISSUE TITLE
Vulkan Support

### ISSUE THREAD

**Issue by nyabinary** [griffi-gh/kubi#6]
Any plans for Vulkan support?

**Comment by griffi-gh** [comment]
yes, there's a work-in-progress `wgpu` branch.  
(wgpu supports vulkan).  
Doesn't even compile yet though (all rendering and gui code needs to be rewritten)

**Comment by griffi-gh** [comment]
gonna give this another try :3

**Comment by nyabinary** [comment]
:3

**Comment by griffi-gh** [comment]
> gonna give this another try :3 (#21)

![kubi_KmQ4kUDm9m](https://github.com/griffi-gh/kubi/assets/45996170/609ffb27-0fd0-42d4-adbd-5bfc57f27b44)

it kinda works

**Comment by nyabinary** [comment]
> yes, there's a work-in-progress `wgpu` branch. (associated pr #7; wgpu supports vulkan). Doesn't even compile yet though (all rendering and gui code needs to be rewritten)

nyaaaaaa
